version: '3.8'

services:
  # Название нашего сервиса (базы данных)
  db:
    # Используем официальный образ PostgreSQL версии 15
    image: postgres:15
    
    # Всегда перезапускать контейнер, если он остановился
    restart: always
    
    # Здесь мы передаем в контейнер данные из вашего .env файла
    # ВАЖНО: Docker Compose автоматически подхватит ваш .env файл
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      
    # Пробрасываем порт. Делает базу данных доступной для подключения с вашего компьютера
    # Формат: "порт_на_вашем_компьютере:порт_внутри_контейнера"
    ports:
      - "${DB_PORT}:5432"
      
    # Этот раздел КРИТИЧЕСКИ ВАЖЕН. Он сохраняет все данные вашей БД
    # на вашем компьютере. Без него все товары исчезнут после перезапуска контейнера.
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Создаем "том" для хранения данных
volumes:
  postgres-data: