groups:
  - name: api-latency-and-errors
    rules:
      - alert: HighP95Latency
        expr: |
          histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{le!="+Inf"}[5m])) by (le)) > 0.2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High p95 latency (>200ms)"
      - alert: HighErrorRate5xx
        expr: |
          sum(rate(http_request_total{status=~"5.."}[5m]))
          /
          sum(rate(http_request_total[5m])) > 0.005
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "5xx error-rate > 0.5%"