name: CI
on:
push:
paths:
- 'backend/**'
- '.github/workflows/ci.yml'
pull_request:
paths:
- 'backend/**'
jobs:
build:
runs-on: ubuntu-latest
services:
postgres:
image: postgres:16
env:
POSTGRES_PASSWORD: postgres
POSTGRES_USER: postgres
POSTGRES_DB: drukarnya
ports: ['5432:5432']
options: >-
--health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5
steps:
- uses: actions/checkout@v4
- uses: pnpm/action-setup@v4
with: { version: 9 }
- name: Install
working-directory: backend
run: pnpm i --frozen-lockfile
- name: Typecheck & build
working-directory: backend
env:
DATABASE_URL: postgresql://postgres:postgres@localhost:5432/drukarnya
run: |
pnpm typecheck
pnpm build
- name: Migrate & seed
working-directory: backend
env:
DATABASE_URL: postgresql://postgres:postgres@localhost:5432/drukarnya
run: |
pnpm migrate
pnpm seed
- name: Lint
working-directory: backend
run: pnpm lint || true